packages:
  - '.'

allowBuilds:
  esbuild: true
  msw: true
  sharp: true
  unrs-resolver: true

overrides:
  hono: 4.12.25
  ora: 9.4.0

onlyBuiltDependencies:
  - esbuild
  - msw
  - sharp
  - unrs-resolver

minimumReleaseAgeExclude:
  - '@sanity/cli-core@2.7.1'
  - '@sanity/cli@7.15.1'
  - '@sanity/client@7.26.0'
  - '@sanity/diff@6.8.0'
  - '@sanity/mutator@6.8.0'
  - '@sanity/schema@6.8.0'
  - '@sanity/types@6.8.0'
  - '@sanity/util@6.8.0'
  - sanity@6.8.0
